CREATE TABLE handbooks (
  id VARCHAR(36) PRIMARY KEY,
  dept VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  edition VARCHAR(50) NOT NULL,
  document_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (dept),
  INDEX (edition)
);
