CREATE TABLE IF NOT EXISTS placements (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    dept VARCHAR(50) NOT NULL, 
    academic_year VARCHAR(20) NOT NULL,
    total_offers INT NOT NULL,
    highest_package DECIMAL(10,2) NOT NULL,
    average_package DECIMAL(10,2) NOT NULL,
    report_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS placement_gallery (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    dept VARCHAR(50) NOT NULL, 
    title VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    caption VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
