CREATE TABLE IF NOT EXISTS workshops (
  id INT AUTO_INCREMENT PRIMARY KEY, 
  dept VARCHAR(50) NOT NULL, 
  title VARCHAR(255) NOT NULL, 
  date_from DATE NOT NULL, 
  date_to DATE NOT NULL, 
  description TEXT, 
  report_url VARCHAR(255), 
  gallery JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
